apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hi0tom2ih-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hi0tom2ih-dotnet-basic-gitops